package com.tony.shoppe.bean;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ty_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class User {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_user.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   用户名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   用户性别，0：男；1：女
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_user.user_sex
     *
     * @mbg.generated
     */
    private Integer userSex;

    /**
     * Database Column Remarks:
     *   用户年龄
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_user.user_age
     *
     * @mbg.generated
     */
    private Integer userAge;

    /**
     * Database Column Remarks:
     *   用户手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_user.user_tel
     *
     * @mbg.generated
     */
    private String userTel;

    /**
     * Database Column Remarks:
     *   用户生日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_user.user_birthday
     *
     * @mbg.generated
     */
    private Date userBirthday;

    /**
     * Database Column Remarks:
     *   用户状态0：不正常，1：正常
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_user.user_state
     *
     * @mbg.generated
     */
    private String userState;

    /**
     * Database Column Remarks:
     *   创建人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_user.create_id
     *
     * @mbg.generated
     */
    private String createId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_user.update_id
     *
     * @mbg.generated
     */
    private String updateId;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_user.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   是否删除1：未删除，0：删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ty_user.delete_state
     *
     * @mbg.generated
     */
    private Byte deleteState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_user.id
     *
     * @return the value of ty_user.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_user.id
     *
     * @param id the value for ty_user.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_user.user_name
     *
     * @return the value of ty_user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_user.user_name
     *
     * @param userName the value for ty_user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_user.user_sex
     *
     * @return the value of ty_user.user_sex
     *
     * @mbg.generated
     */
    public Integer getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_user.user_sex
     *
     * @param userSex the value for ty_user.user_sex
     *
     * @mbg.generated
     */
    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_user.user_age
     *
     * @return the value of ty_user.user_age
     *
     * @mbg.generated
     */
    public Integer getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_user.user_age
     *
     * @param userAge the value for ty_user.user_age
     *
     * @mbg.generated
     */
    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_user.user_tel
     *
     * @return the value of ty_user.user_tel
     *
     * @mbg.generated
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_user.user_tel
     *
     * @param userTel the value for ty_user.user_tel
     *
     * @mbg.generated
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel == null ? null : userTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_user.user_birthday
     *
     * @return the value of ty_user.user_birthday
     *
     * @mbg.generated
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_user.user_birthday
     *
     * @param userBirthday the value for ty_user.user_birthday
     *
     * @mbg.generated
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_user.user_state
     *
     * @return the value of ty_user.user_state
     *
     * @mbg.generated
     */
    public String getUserState() {
        return userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_user.user_state
     *
     * @param userState the value for ty_user.user_state
     *
     * @mbg.generated
     */
    public void setUserState(String userState) {
        this.userState = userState == null ? null : userState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_user.create_id
     *
     * @return the value of ty_user.create_id
     *
     * @mbg.generated
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_user.create_id
     *
     * @param createId the value for ty_user.create_id
     *
     * @mbg.generated
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_user.create_time
     *
     * @return the value of ty_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_user.create_time
     *
     * @param createTime the value for ty_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_user.update_id
     *
     * @return the value of ty_user.update_id
     *
     * @mbg.generated
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_user.update_id
     *
     * @param updateId the value for ty_user.update_id
     *
     * @mbg.generated
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_user.update_time
     *
     * @return the value of ty_user.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_user.update_time
     *
     * @param updateTime the value for ty_user.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ty_user.delete_state
     *
     * @return the value of ty_user.delete_state
     *
     * @mbg.generated
     */
    public Byte getDeleteState() {
        return deleteState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ty_user.delete_state
     *
     * @param deleteState the value for ty_user.delete_state
     *
     * @mbg.generated
     */
    public void setDeleteState(Byte deleteState) {
        this.deleteState = deleteState;
    }
}